version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: webserver_nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: webserver_php
    volumes:
      - ./html:/var/www/html



  # Optional: ใช้ phpmyadmin ถ้าเชื่อมกับ MySQL
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   container_name: webserver_db
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: pass
  #   volumes:
  #     - db_data:/var/lib/mysql

# volumes:
#   db_data:
